<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVvF5Mwx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVvF5Mwx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVvF5Mwx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVvF5Mwx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVvF5Mwx\App_KernelDevDebugContainer([
    'container.build_hash' => 'VvF5Mwx',
    'container.build_id' => '8e98df0f',
    'container.build_time' => 1681460573,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVvF5Mwx');
