<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXVZLiqv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXVZLiqv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXVZLiqv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXVZLiqv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXVZLiqv\App_KernelDevDebugContainer([
    'container.build_hash' => 'XVZLiqv',
    'container.build_id' => 'fd008966',
    'container.build_time' => 1681210811,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXVZLiqv');
