<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNIEe39s\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNIEe39s/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNIEe39s.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNIEe39s\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNIEe39s\App_KernelDevDebugContainer([
    'container.build_hash' => 'NIEe39s',
    'container.build_id' => '586c84f0',
    'container.build_time' => 1681484124,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNIEe39s');
